# Utiliser la dernière version d'Ubuntu comme base
FROM ubuntu:latest

# Mettre à jour APT et mettre à niveau les paquets installés
RUN apt-get update && apt-get upgrade -y

# Indiquer la commande à exécuter quand le conteneur démarre
CMD echo "Hello, World!"
